site_name: Neuranimation Package
site_author: Sebastian Silva, Sergio Sugahara, Willy Ugarte
repo_url: https://github.com/SergioSugaharaC/Neuranimations
repo_name: Neuranimations
nav:
  - Home: index.md
  - PFNN: pfnn.md
  - Installation: installation.md
  - Usage: usage.md
  - About: about.md
theme: 
  name: 'material'
  locale: en
extra:
  version: 1.0.0
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - abbr
  - admonition
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js